### ISSUE TITLE
谢谢老板的分享！有个小问题！一直提示窗口大小不匹配怎么办呢？

### ISSUE THREAD

**Issue by LIUHUGEDOG** [AquamarineCyan/Onmyoji_Python#1]
我是个新手 不太会用github，下载之后用管理员身份打开一直提示窗口大小不匹配

**Comment by AquamarineCyan** [comment]
首先确保是默认尺寸，即没有自行改过应用路径下的`neox.xml`
尝试修改系统设置里的缩放
找到应用启动程序（安装路径下的`Launch.exe`），右击--属性--兼容性--更改高DPI设置--高DPI缩放行为，先每个尝试一下吧
后续考虑写个F&Q
