### ISSUE TITLE
是安装的python 版本太高了吗

### ISSUE THREAD

**Issue by fulifuli666** [AquamarineCyan/Onmyoji_Python#3]
ERROR: Could not find a version that satisfies the requirement Python>=3.10 (from versions: none)
ERROR: No matching distribution found for Python>=3.10

**Comment by AquamarineCyan** [comment]
`PySide6` 在 `poetry`环境中安装会锁定 `python = ">=3.10,<3.11"`
下面是2种可能的方法：
- 可以尝试先注释 `pyproject.toml` 中 `pyside6 = "6.3.0"` ，后使用 `pip install PySide6` 安装环境
- 不使用 `poetry` 虚拟环境，通过pip安装环境 `pip install -r requirements.txt`

**Comment by AquamarineCyan** [comment]
> ERROR: Could not find a version that satisfies the requirement Python>=3.10 (from versions: none) ERROR: No matching distribution found for Python>=3.10

是我的 `requirements.txt` 写法问题，已经修改了
