### ISSUE TITLE
作者大大可以更新斗技的部分吗？

### ISSUE THREAD

**Issue by liyifan1996** [AquamarineCyan/Onmyoji_Python#6]
作者大大可以更新斗技的部分吗？只需要自动斗技就可以了，感谢大大

**Comment by AquamarineCyan** [comment]
已经提交了初稿代码 [03b0613](03b061317f2a1a2c2240dbd568734bc177fd3d35)，仍需要一些测试，过几天发版

**Comment by AquamarineCyan** [comment]
已发版`v1.8.4`
